---
- name: Backup Lab Devices
  hosts: homelab
  gather_facts: no
  connection: network_cli
  vars:
    backup_dir: "/data/device_backups/{{ inventory_hostname }}/"

  tasks:

    - name: Ensure backup directory exists
      delegate_to: localhost
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Backup Cisco running-config
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ backup_dir }}{{ inventory_hostname }}_{{ lookup('pipe','date +%Y-%m-%d') }}.cfg"
      when: ansible_network_os == 'ios'

    - name: Backup Juniper config
      junos_config:
        backup: yes
        backup_options: 
	  filename: "{{ backup_dir }}{{ inventory_hostname }}_{{ lookup('pipe','date +%Y-%m-%d') }}.cfg"
      when: ansible_network_os == 'junos'

