---
- name: Backup Switch and Router Configurations
  hosts: switches
  gather_facts: no
  vars:
    backup_dir: "/data/device_backups/{{ inventory_hostname }}/"

  tasks:
    - name: Ensure backup directory exists
      delegate_to: localhost
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    # Cisco IOS
    - name: Save Cisco running config to startup config
      ios_command:
        commands:
          - write memory
      when: ansible_network_os == 'ios'

    - name: Backup Cisco running-config
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ backup_dir }}{{ inventory_hostname }}_{{ lookup('pipe','date +%Y-%m-%d') }}.cfg"
      when: ansible_network_os == 'ios'

    # Juniper JunOS
    - name: Backup Juniper config
      junos_config:
        backup: yes
        backup_options: 
          filename: "{{ backup_dir }}{{ inventory_hostname }}_{{ lookup('pipe','date +%Y-%m-%d') }}.cfg"
      when: ansible_network_os == 'junos'

